/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CurrencySymbol = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Portfolio = IDL.Record({
  'ada' : IDL.Float64,
  'bnb' : IDL.Float64,
  'btc' : IDL.Float64,
  'eth' : IDL.Float64,
  'sol' : IDL.Float64,
});
export const TransactionId = IDL.Nat;
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'transactionType' : IDL.Variant({ 'receive' : IDL.Null, 'send' : IDL.Null }),
  'coin' : CurrencySymbol,
  'usdValue' : IDL.Float64,
  'timestamp' : Time,
  'amount' : IDL.Float64,
  'counterpartyAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func(
      [
        CurrencySymbol,
        IDL.Variant({ 'receive' : IDL.Null, 'send' : IDL.Null }),
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBalance' : IDL.Func([CurrencySymbol, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CurrencySymbol = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Portfolio = IDL.Record({
    'ada' : IDL.Float64,
    'bnb' : IDL.Float64,
    'btc' : IDL.Float64,
    'eth' : IDL.Float64,
    'sol' : IDL.Float64,
  });
  const TransactionId = IDL.Nat;
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'transactionType' : IDL.Variant({
      'receive' : IDL.Null,
      'send' : IDL.Null,
    }),
    'coin' : CurrencySymbol,
    'usdValue' : IDL.Float64,
    'timestamp' : Time,
    'amount' : IDL.Float64,
    'counterpartyAddress' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func(
        [
          CurrencySymbol,
          IDL.Variant({ 'receive' : IDL.Null, 'send' : IDL.Null }),
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBalance' : IDL.Func([CurrencySymbol, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };